#!/usr/bin/env python3
"""Generate docs/design/TOC.md — a per-section table of contents for the whole
design tree.

For every tracked Markdown file under docs/design/ (excluding the meta files
TOC.md, AGENTS.md, CLAUDE.md), emit the file's H1 as a linked entry and each of
its H2 sections as an anchor link. Slugs come from scripts/check-doc-xrefs.py's
GitHub-compatible slugger (including the duplicate-slug -1/-2 dedup), so every
link the generator writes is exactly what `make lint-docs` validates.

Regenerate after any heading change in docs/design/:

    scripts/generate-doc-toc.py

The output is deterministic: directories in layer order, files alphabetical
within a directory (top-level files in reading-priority order).
"""

import importlib.util
import re
import subprocess
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parent
ROOT = SCRIPTS.parent
DESIGN = ROOT / "docs" / "design"

_spec = importlib.util.spec_from_file_location("xrefs", SCRIPTS / "check-doc-xrefs.py")
_xrefs = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_xrefs)
slugify = _xrefs.slugify
iter_content_lines = _xrefs._iter_content_lines

ATX_RE = re.compile(r"^(#{1,6})\s+(.*?)\s*#*\s*$")
MD_DECOR_RE = re.compile(r"[*_`]")

EXCLUDE = {"TOC.md", "AGENTS.md", "CLAUDE.md"}

# Layer order for directories (repo-relative to docs/design); unknown
# directories sort after these, alphabetically.
DIR_ORDER = [
    ".",
    "primitives/data/sad",
    "primitives/data/event-logs",
    "primitives/data/event-logs/kel",
    "primitives/data/event-logs/iel",
    "primitives/data/event-logs/sel",
    "substrate/federation",
    "primitives/policy",
    "primitives/protocols",
    "features",
    "substrate/infrastructure",
    "example-applications",
]

# Reading-priority order for the top-level files; the rest follow alphabetically.
TOP_ORDER = [
    "README.md",
    "system-thesis.md",
    "glossary.md",
    "protocol-doctrine.md",
    "residuals.md",
    "monitoring.md",
]


def tracked_design_files():
    out = subprocess.run(
        ["git", "ls-files", "--", "docs/design/*.md", "docs/design/**/*.md"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.splitlines()
    files = []
    for rel in sorted(set(out)):
        p = ROOT / rel
        if p.name in EXCLUDE:
            continue
        files.append(p)
    return files


def headings_of(path):
    """(level, text, anchor) for each heading, with GitHub dedup numbering."""
    seen = {}
    result = []
    for _lineno, line in iter_content_lines(path):
        m = ATX_RE.match(line)
        if not m:
            continue
        level = len(m.group(1))
        text = MD_DECOR_RE.sub("", m.group(2)).strip()
        base = slugify(m.group(2))
        n = seen.get(base, 0)
        seen[base] = n + 1
        anchor = base if n == 0 else f"{base}-{n}"
        result.append((level, text, anchor))
    return result


def dir_key(rel_dir):
    try:
        return (0, DIR_ORDER.index(rel_dir))
    except ValueError:
        return (1, rel_dir)


def file_key(path):
    if path.parent == DESIGN:
        try:
            return (0, TOP_ORDER.index(path.name))
        except ValueError:
            return (1, path.name)
    return (1, path.name)


def main():
    by_dir = {}
    for p in tracked_design_files():
        rel_dir = str(p.parent.relative_to(DESIGN)) if p.parent != DESIGN else "."
        by_dir.setdefault(rel_dir, []).append(p)

    lines = [
        "# Design-tree table of contents",
        "",
        "Every file in the design tree, with a link to each of its sections — the lookup map",
        "[`AGENTS.md`](AGENTS.md) navigates by. Generated by `scripts/generate-doc-toc.py`;",
        "regenerate after any heading change. The narrative reading order is",
        "[`README.md`](README.md); this file is for going straight to a section.",
    ]

    for rel_dir in sorted(by_dir, key=dir_key):
        title = "top-level" if rel_dir == "." else rel_dir
        lines += ["", f"## {title}"]
        for p in sorted(by_dir[rel_dir], key=file_key):
            rel = p.relative_to(DESIGN).as_posix()
            hs = headings_of(p)
            h1 = next((t for level, t, _ in hs if level == 1), p.name)
            lines += ["", f"### [`{rel}`]({rel}) — {h1}", ""]
            h2s = [(t, a) for level, t, a in hs if level == 2]
            if not h2s:
                lines.append("- _no sections_")
            for text, anchor in h2s:
                lines.append(f"- [{text}]({rel}#{anchor})")

    (DESIGN / "TOC.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    n_files = sum(len(v) for v in by_dir.values())
    print(f"TOC.md: {n_files} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
